name: Deploy Flask app to Ubuntu server
env:
  AWS_REGION_NAME: us-east-1


on:
  push:
    branches: 
     - main
     
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
      
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}
        
    - name: Check versions
      run: |
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "sudo cat /home/ubuntu/.ssh/authorized_keys"
